# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28eb7c2b675eff61f619156d4ecef9802689467793558b969cd7f6ac065c58f6d7a6a22d1175639a4a8eb9d81adbdea8c46220898de26660811d0073c21515b7

test:
  secret_key_base: 176fc85f4193b8f3658b491d8451e1e5dfb6f12ac07ba8bef8d43de87cc71792d9c7a92ebea737ee9da7f4a871da7738ce6cf02a5b496a34e4982e493617ec9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
